# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_patrols_from_combined_params = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_patrols_from_combined_params",  # 🧪
)  # 🧪

get_patrol_observations_from_patrols_df_and_combined_params = (
    create_func_magicmock(  # 🧪
        anchor="ecoscope.platform.tasks.io",  # 🧪
        func_name="get_patrol_observations_from_patrols_df_and_combined_params",  # 🧪
    )
)  # 🧪
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)

get_event_type_display_names_from_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_event_type_display_names_from_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import create_meshgrid as create_meshgrid
from ecoscope.platform.tasks.analysis import (
    dataframe_column_mean as dataframe_column_mean,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_bool_var as set_bool_var
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import fill_na as fill_na
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.skip import invert_bool as invert_bool
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    calculate_encounter_rate_grid as calculate_encounter_rate_grid,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    drop_inactive_grid_cells as drop_inactive_grid_cells,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    mask_low_effort_cells as mask_low_effort_cells,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    er_patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            sub_page_size=100,
            patrols_overlap_daterange=True,
            include_null_geometry=False,
            **(params.get("er_patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_and_events_params,
            **(params.get("prefetch_patrols") or {}),
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    event_type_display_names = (
        task(get_event_type_display_names_from_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("event_type_display_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            events_gdf=patrol_events,
            append_category_names="duplicates",
            **(params.get("event_type_display_names") or {}),
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    convert_patrols_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_patrols_to_tz") or {}),
        )
        .call()
    )

    convert_events_to_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_type_display_names,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_to_tz") or {}),
        )
        .call()
    )

    drop_extra_prefix_obs = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_to_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_obs") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_obs,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=filter_patrol_obs, **(params.get("patrol_traj") or {}))
        .call()
    )

    drop_extra_prefix_traj = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_traj") or {}),
        )
        .call()
    )

    customize_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("customize_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_traj,
            rename_columns={},
            drop_columns=["id"],
            retain_columns=[],
            raise_if_not_found=False,
            **(params.get("customize_columns") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    set_patrol_traj_color_column = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_patrol_traj_color_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("set_patrol_traj_color_column") or {}))
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=customize_columns,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_rename_grouper_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_grouper_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            drop_columns=["patrol_type"],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={"patrol_type__value": "patrol_type"},
            **(params.get("traj_rename_grouper_cols") or {}),
        )
        .call()
    )

    traj_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_grouper_cols,
            colormap=[
                "#FF9600",
                "#F23B0E",
                "#A100CB",
                "#F04564",
                "#03421A",
                "#3089FF",
                "#E26FFF",
                "#8C1700",
                "#002960",
                "#FFD000",
                "#B62879",
                "#680078",
                "#005A56",
                "#0056C7",
                "#331878",
                "#E76826",
            ],
            input_column_name=set_patrol_traj_color_column,
            output_column_name="patrol_traj_colormap",
            **(params.get("traj_colormap") or {}),
        )
        .call()
    )

    patrol_effort_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("patrol_effort_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=customize_columns,
            groupby_cols=["patrol_id"],
            summary_params=[
                {
                    "display_name": "total_dist_m",
                    "aggregator": "sum",
                    "column": "dist_meters",
                },
                {
                    "display_name": "total_time_s",
                    "aggregator": "sum",
                    "column": "timespan_seconds",
                },
            ],
            reset_index=True,
            **(params.get("patrol_effort_summary") or {}),
        )
        .call()
    )

    drop_extra_prefix_events = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_extra_prefix_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_tz,
            prefix="extra__",
            duplicate_strategy="suffix",
            **(params.get("drop_extra_prefix_events") or {}),
        )
        .call()
    )

    filter_patrol_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_extra_prefix_events,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("filter_patrol_events") or {}),
        )
        .call()
    )

    events_with_effort = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("events_with_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=filter_patrol_events,
            right=patrol_effort_summary,
            how="left",
            on="patrol_id",
            left_on=None,
            right_on=None,
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("events_with_effort") or {}),
        )
        .call()
    )

    pe_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("pe_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_effort,
            time_col="patrol_start_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("pe_add_temporal_index") or {}),
        )
        .call()
    )

    pe_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("pe_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_add_temporal_index,
            input_column_name="event_type",
            colormap="tab20b",
            output_column_name="event_type_colormap",
            **(params.get("pe_colormap") or {}),
        )
        .call()
    )

    traj_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("traj_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_colormap,
            columns=["patrol_serial_number", "patrol_type"],
            **(params.get("traj_cols_to_string") or {}),
        )
        .call()
    )

    pe_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("pe_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_colormap,
            columns=["patrol_serial_number", "patrol_type"],
            **(params.get("pe_cols_to_string") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_cols_to_string,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    split_pe_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_pe_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_cols_to_string,
            groupers=groupers,
            **(params.get("split_pe_groups") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    zipped_events_traj = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zipped_events_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[split_pe_groups, split_traj_groups],
            **(params.get("zipped_events_traj") or {}),
        )
        .call()
    )

    encounter_meshgrid = (
        task(create_meshgrid)
        .validate()
        .set_task_instance_id("encounter_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=traj_cols_to_string,
            intersecting_only=True,
            **(params.get("encounter_meshgrid") or {}),
        )
        .call()
    )

    encounter_rate_grid = (
        task(calculate_encounter_rate_grid)
        .validate()
        .set_task_instance_id("encounter_rate_grid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=encounter_meshgrid, **(params.get("encounter_rate_grid") or {})
        )
        .mapvalues(argnames=["feature_layers"], argvalues=zipped_events_traj)
    )

    drop_inactive_cells = (
        task(drop_inactive_grid_cells)
        .validate()
        .set_task_instance_id("drop_inactive_cells")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_column="event_count",
            patrol_effort_column="patrol_effort_km",
            **(params.get("drop_inactive_cells") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=encounter_rate_grid)
    )

    fill_nan_rate = (
        task(fill_na)
        .validate()
        .set_task_instance_id("fill_nan_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(columns=["density"], value=0, **(params.get("fill_nan_rate") or {}))
        .mapvalues(argnames=["df"], argvalues=drop_inactive_cells)
    )

    sort_rate_values = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_rate_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("sort_rate_values") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=fill_nan_rate)
    )

    classify_rate = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("classify_rate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="rate_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 2},
            **(params.get("classify_rate") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_rate_values)
    )

    rate_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("rate_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="rate_bins",
            colormap="RdYlGn_r",
            output_column_name="rate_colormap",
            **(params.get("rate_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=classify_rate)
    )

    mask_low_effort = (
        task(mask_low_effort_cells)
        .validate()
        .set_task_instance_id("mask_low_effort")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrol_effort_column="patrol_effort_km",
            color_column="rate_colormap",
            label_column="rate_bins",
            grey_color=[128, 128, 128, 255],
            grey_label="< 200 m patrol effort",
            **(params.get("mask_low_effort") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=rate_colormap)
    )

    rename_rate_col = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_rate_col")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "density": "Encounter Rate (per km)",
                "event_count": "Events",
                "patrol_effort_km": "Patrol Effort (km)",
            },
            raise_if_not_found=True,
            **(params.get("rename_rate_col") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=mask_low_effort)
    )

    rate_polygon_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("rate_polygon_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "rate_colormap",
                "get_line_width": 0,
                "opacity": 0.4,
            },
            legend={"label_column": "rate_bins", "color_column": "rate_colormap"},
            tooltip_columns=["Encounter Rate (per km)", "Events", "Patrol Effort (km)"],
            **(params.get("rate_polygon_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_rate_col)
    )

    set_rate_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rate_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Encounter Rate Map", **(params.get("set_rate_map_title") or {}))
        .call()
    )

    rate_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("rate_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Encounter Rate (per km)",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_rate_map_title,
            **(params.get("rate_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=rate_polygon_layer)
    )

    rate_ecomap_html_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("rate_ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="encounter_rate_map",
            **(params.get("rate_ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=rate_ecomap)
    )

    rate_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("rate_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_rate_map_title, **(params.get("rate_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=rate_ecomap_html_urls)
    )

    grouped_rate_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_rate_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=rate_map_widgets, **(params.get("grouped_rate_map_widget") or {})
        )
        .call()
    )

    set_patrol_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_patrol_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Patrol Trajectories and Events Map",
            **(params.get("set_patrol_map_title") or {}),
        )
        .call()
    )

    rename_traj_display_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_traj_display_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "patrol_serial_number": "Patrol Serial",
                "patrol_type__display": "Patrol Type",
                "segment_start": "Start Time",
                "timespan_seconds": "Duration (s)",
                "speed_kmhr": "Speed (kph)",
            },
            **(params.get("rename_traj_display_cols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    rename_event_display_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_event_display_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            raise_if_not_found=False,
            rename_columns={
                "patrol_serial_number": "Patrol Serial",
                "event_type": "Event Type",
                "time": "Event Time",
            },
            **(params.get("rename_event_display_cols") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_pe_groups)
    )

    traj_map_layers = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("traj_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_width": 3,
                "width_units": "pixels",
                "color_column": "patrol_traj_colormap",
            },
            legend={
                "label_column": set_patrol_traj_color_column,
                "color_column": "patrol_traj_colormap",
            },
            tooltip_columns=[
                "Patrol Serial",
                "Patrol Type",
                "Start Time",
                "Duration (s)",
                "Speed (kph)",
            ],
            **(params.get("traj_map_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_traj_display_cols)
    )

    event_map_layers = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("event_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend=None,
            tooltip_columns=["Patrol Serial", "Event Type", "Event Time"],
            **(params.get("event_map_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_event_display_cols)
    )

    combined_traj_event_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("combined_traj_event_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[traj_map_layers, event_map_layers],
            **(params.get("combined_traj_event_layers") or {}),
        )
        .call()
    )

    patrol_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("patrol_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": set_patrol_traj_color_column,
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_patrol_map_title,
            **(params.get("patrol_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=combined_traj_event_layers)
    )

    patrol_ecomap_html_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="patrol_map",
            **(params.get("patrol_ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=patrol_ecomap)
    )

    patrol_map_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_map_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_patrol_map_title, **(params.get("patrol_map_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=patrol_ecomap_html_urls)
    )

    grouped_patrol_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_patrol_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=patrol_map_widgets,
            **(params.get("grouped_patrol_map_widget") or {}),
        )
        .call()
    )

    set_total_hours_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_total_hours_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Total Patrol Hours", **(params.get("set_total_hours_title") or {})
        )
        .call()
    )

    set_rate_hr_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rate_hr_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Events Per Hour", **(params.get("set_rate_hr_title") or {}))
        .call()
    )

    set_total_km_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_total_km_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Total Patrol Km", **(params.get("set_total_km_title") or {}))
        .call()
    )

    set_rate_km_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_rate_km_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Events Per Km", **(params.get("set_rate_km_title") or {}))
        .call()
    )

    set_total_events_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_total_events_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Total Events", **(params.get("set_total_events_title") or {}))
        .call()
    )

    encounter_stats_sql = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("encounter_stats_sql")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sanitize=True,
            query="SELECT\n  CAST(COUNT(*) AS FLOAT) AS total_events,\n  (SELECT SUM(t) FROM (SELECT DISTINCT patrol_id, total_time_s AS t FROM df)) / 3600.0 AS total_hours,\n  CAST(COUNT(*) AS FLOAT) * 3600.0 / NULLIF(\n    (SELECT SUM(t) FROM (SELECT DISTINCT patrol_id, total_time_s AS t FROM df)),\n    0\n  ) AS events_per_hour,\n  (SELECT SUM(d) FROM (SELECT DISTINCT patrol_id, total_dist_m AS d FROM df)) / 1000.0 AS total_km,\n  CAST(COUNT(*) AS FLOAT) * 1000.0 / NULLIF(\n    (SELECT SUM(d) FROM (SELECT DISTINCT patrol_id, total_dist_m AS d FROM df)),\n    0\n  ) AS events_per_km\nFROM df",
            columns=["patrol_id", "total_dist_m", "total_time_s"],
            **(params.get("encounter_stats_sql") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_pe_groups)
    )

    total_events_value = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("total_events_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="total_events", **(params.get("total_events_value") or {}))
        .mapvalues(argnames=["df"], argvalues=encounter_stats_sql)
    )

    total_hours_value = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("total_hours_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="total_hours", **(params.get("total_hours_value") or {}))
        .mapvalues(argnames=["df"], argvalues=encounter_stats_sql)
    )

    rate_per_hr_value = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("rate_per_hr_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="events_per_hour", **(params.get("rate_per_hr_value") or {})
        )
        .mapvalues(argnames=["df"], argvalues=encounter_stats_sql)
    )

    total_km_value = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("total_km_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="total_km", **(params.get("total_km_value") or {}))
        .mapvalues(argnames=["df"], argvalues=encounter_stats_sql)
    )

    rate_per_km_value = (
        task(dataframe_column_mean)
        .validate()
        .set_task_instance_id("rate_per_km_value")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="events_per_km", **(params.get("rate_per_km_value") or {}))
        .mapvalues(argnames=["df"], argvalues=encounter_stats_sql)
    )

    total_hours_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_hours_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_total_hours_title,
            decimal_places=2,
            **(params.get("total_hours_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_hours_value)
    )

    rate_hr_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("rate_hr_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_rate_hr_title,
            decimal_places=2,
            **(params.get("rate_hr_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=rate_per_hr_value)
    )

    total_km_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_km_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_total_km_title,
            decimal_places=2,
            **(params.get("total_km_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_km_value)
    )

    rate_km_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("rate_km_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_rate_km_title,
            decimal_places=2,
            **(params.get("rate_km_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=rate_per_km_value)
    )

    grouped_total_hours_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_total_hours_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_hours_widget,
            **(params.get("grouped_total_hours_widget") or {}),
        )
        .call()
    )

    grouped_rate_hr_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_rate_hr_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=rate_hr_widget, **(params.get("grouped_rate_hr_widget") or {}))
        .call()
    )

    grouped_total_km_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_total_km_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_km_widget, **(params.get("grouped_total_km_widget") or {})
        )
        .call()
    )

    total_events_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_total_events_title,
            decimal_places=0,
            **(params.get("total_events_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_events_value)
    )

    grouped_rate_km_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_rate_km_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=rate_km_widget, **(params.get("grouped_rate_km_widget") or {}))
        .call()
    )

    grouped_total_events_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_total_events_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_events_widget,
            **(params.get("grouped_total_events_widget") or {}),
        )
        .call()
    )

    persist_patrol_traj = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params.get("persist_patrol_traj") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    persist_patrol_events = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params.get("persist_patrol_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_pe_groups)
    )

    set_enable_report = (
        task(set_bool_var)
        .validate()
        .set_task_instance_id("set_enable_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("set_enable_report") or {}))
        .call()
    )

    skip_report = (
        task(invert_bool)
        .validate()
        .set_task_instance_id("skip_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(value=set_enable_report, **(params.get("skip_report") or {}))
        .call()
    )

    report_stats_sql = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("report_stats_sql")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sanitize=True,
            query='SELECT\n  CAST(COUNT(*) AS FLOAT) AS "Total Events",\n  ROUND((SELECT SUM(t) FROM (SELECT DISTINCT patrol_id, total_time_s AS t FROM df)) / 3600.0, 2) AS "Total Patrol Hours",\n  ROUND(CAST(COUNT(*) AS FLOAT) * 3600.0 / NULLIF(\n    (SELECT SUM(t) FROM (SELECT DISTINCT patrol_id, total_time_s AS t FROM df)),\n    0\n  ), 2) AS "Events Per Hour",\n  ROUND((SELECT SUM(d) FROM (SELECT DISTINCT patrol_id, total_dist_m AS d FROM df)) / 1000.0, 2) AS "Total Patrol Km",\n  ROUND(CAST(COUNT(*) AS FLOAT) * 1000.0 / NULLIF(\n    (SELECT SUM(d) FROM (SELECT DISTINCT patrol_id, total_dist_m AS d FROM df)),\n    0\n  ), 2) AS "Events Per Km"\nFROM df',
            columns=["patrol_id", "total_dist_m", "total_time_s"],
            **(params.get("report_stats_sql") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_pe_groups)
    )

    create_encounter_report = (
        task(create_docx)
        .validate()
        .set_task_instance_id("create_encounter_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            skip=skip_report,
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {
                        "item_type": "table",
                        "key": "encounter_stats",
                        "value": report_stats_sql,
                        "merge_groups": True,
                    },
                    {
                        "item_type": "image",
                        "key": "patrol_maps",
                        "value": patrol_ecomap_html_urls,
                        "screenshot_config": {
                            "wait_for_timeout": 20000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "rate_maps",
                        "value": rate_ecomap_html_urls,
                        "screenshot_config": {
                            "wait_for_timeout": 20000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                ]
            },
            groupers=groupers,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="encounter_rate_report",
            **(params.get("create_encounter_report") or {}),
        )
        .call()
    )

    encounter_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("encounter_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                grouped_total_events_widget,
                grouped_total_hours_widget,
                grouped_rate_hr_widget,
                grouped_total_km_widget,
                grouped_rate_km_widget,
                grouped_patrol_map_widget,
                grouped_rate_map_widget,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("encounter_dashboard") or {}),
        )
        .call()
    )

    return encounter_dashboard
