# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class StatusEnum(str, Enum):
    active = "active"
    overdue = "overdue"
    done = "done"
    cancelled = "cancelled"


class ErPatrolAndEventsParams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    patrol_types: list[str] = Field(
        ...,
        description='Specify the patrol type(s) to analyze. Enter the "Patrol Types" value for each patrol type — one per field (e.g. "ecoscope_patrol"). Leave empty to include all patrol types.',
        title="Patrol Types",
    )
    event_types: list[str] = Field(
        ...,
        description='Specify the event type(s) to include. Enter the "Event Types" value for each event type — one per field (e.g. "wildlife_sighting_rep"). Leave empty to include all event types.',
        title="Event Types",
    )
    status: list[StatusEnum] | None = Field(
        ["done"],
        description="Choose to analyze patrols with a certain status. If left empty, patrols of all status will be analyzed",
        title="Patrol Status",
    )


class PatrolAndEventTypes(BaseModel):
    er_patrol_and_events_params: ErPatrolAndEventsParams | None = Field(None, title="")


class SetPatrolTrajColorColumn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Select the patrol observation attribute to use for categorizing and coloring patrol trajectories on the generated maps.",
        title="Category",
    )


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: constr(pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)") | None = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: list[BaseMaps | BaseMaps1 | BaseMaps2 | BaseMaps3 | BaseMaps4 | BaseMaps5 | BaseMaps6] | None = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title="Map Base Layers",
    )


class Filetype(str, Enum):
    csv = "csv"
    parquet = "parquet"


class PersistPatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: list[Filetype] | None = Field(
        ["parquet"], description="The output format", title="Filetypes"
    )
    filename_prefix: str | None = Field(
        "patrol_trajectories",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class PersistPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: list[Filetype] | None = Field(
        ["parquet"], description="The output format", title="Filetypes"
    )
    filename_prefix: str | None = Field(
        "patrol_events",
        description="            Optional filename prefix to persist text to within the `root_path`.\n            We will always add a suffix based on the dataframe content hash to avoid duplicates.\n            ",
        title="Filename Prefix",
    )


class SetSkipReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: bool = Field(
        ...,
        description="Skip generating the Word document report. Uncheck to include a summary report in the output.",
        title="",
    )


class CreateEncounterReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class GenerateReport(BaseModel):
    set_skip_report: SetSkipReport | None = Field(None, title="Skip Report Generation")
    create_encounter_report: CreateEncounterReport | None = Field(
        None, title="Create Encounter Rate Report"
    )


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: confloat(ge=0.001) | None = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: confloat(gt=0.001) | None = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: confloat(ge=1.0) | None = Field(1, title="Minimum Segment Duration (Seconds)")
    max_time_secs: confloat(gt=1.0) | None = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: confloat(gt=0.001) | None = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: confloat(gt=0.001) | None = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str | None = Field(None, title="Index Name")


class BoundingBox(BaseModel):
    min_y: float | None = Field(-90.0, title="Min Latitude")
    max_y: float | None = Field(90.0, title="Max Latitude")
    min_x: float | None = Field(-180.0, title="Min Longitude")
    max_x: float | None = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class AutoScaleOrCustom(str, Enum):
    Auto_scale = "Auto-scale"


class AutoScaleGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Auto-scale"] = Field("Auto-scale", title="Grid Cell Size")


class AutoScaleOrCustom1(str, Enum):
    Customize = "Customize"


class CustomGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Customize"] = Field("Customize", title="Grid Cell Size")
    grid_cell_size: confloat(lt=10000.0, gt=0.0) | None = Field(
        5000,
        description="Define the resolution of the raster grid (in the unit of measurement defined by the coordinate reference system set below). A smaller grid cell size provides more detail, while a larger size generalizes the data.",
        title="Custom Grid Cell Size",
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class PatrolTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: TrajectorySegmentFilter | None = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class ProcessPatrolObservations(BaseModel):
    patrol_traj: PatrolTraj | None = Field(None, title="Trajectory Segment Filter")
    groupers: Groupers | None = Field(None, title="Group Data")
    set_patrol_traj_color_column: SetPatrolTrajColorColumn | None = Field(
        None, title="Style Trajectory By Category"
    )


class FilterPatrolEvents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: BoundingBox | None = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: list[Coordinate] | None = Field(
        [],
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )


class ProcessPatrolEvents(BaseModel):
    filter_patrol_events: FilterPatrolEvents | None = Field(
        None, title="Apply Coordinate Filter to Patrol Events"
    )


class EncounterMeshgrid(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auto_scale_or_custom_cell_size: AutoScaleGridCellSize | CustomGridCellSize | None = (
        Field(
            default_factory=lambda: AutoScaleGridCellSize.model_validate(
                {"auto_scale_or_custom": "Auto-scale"}
            ),
            title="Grid Cell Size",
        )
    )
    crs: str | None = Field(
        "EPSG:3857",
        description="The coordinate reference system in which to perform the calculation, must be a valid CRS authority code, for example ESRI:53042",
        title="Coordinate Reference System",
    )


class EncounterRateMap(BaseModel):
    encounter_meshgrid: EncounterMeshgrid | None = Field(None, title="")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    er_client_name: ErClientName | None = Field(None, title="Data Source")
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    Patrol_and_Event_Types: PatrolAndEventTypes | None = Field(
        None, alias="Patrol and Event Types", description=" "
    )
    Process_Patrol_Observations: ProcessPatrolObservations | None = Field(
        None,
        alias="Process Patrol Observations",
        description="Process patrol observations into trajectories.",
    )
    Process_Patrol_Events: ProcessPatrolEvents | None = Field(
        None,
        alias="Process Patrol Events",
        description="Process patrol events by applying filters, merging effort data, and indexing.",
    )
    base_map_defs: BaseMapDefs | None = Field(None, title="Map Base Layers")
    Encounter_Rate_Map: EncounterRateMap | None = Field(
        None,
        alias="Encounter Rate Map",
        description="These settings generate a grid-based heatmap showing encounter rate (events per unit of patrol effort in each cell).",
    )
    persist_patrol_traj: PersistPatrolTraj | None = Field(
        None, title="Persist Patrol Trajectories"
    )
    persist_patrol_events: PersistPatrolEvents | None = Field(
        None, title="Persist Patrol Events"
    )
    Generate_Report: GenerateReport | None = Field(
        None,
        alias="Generate Report",
        description="Generate a Word document report summarizing encounter rate results.",
    )
